version: "3"
services:
  adguardhome:
    image: adguard/adguardhome:latest
    container_name: adguardhome
    labels:
      - "diun.enable=true"
    network_mode: nginx-proxy-manager_default
    ports:
      - 53:53/tcp
      - 53:53/udp
      #- 784:784/udp
      #- 853:853/tcp
      - 3555:3000/tcp
      - 4430:443/tcp
    volumes:
      - /docker/adguardhome/workdir:/opt/adguardhome/work
      - /docker/adguardhome/confdir:/opt/adguardhome/conf
    restart: unless-stopped

#Si doh activé : acceder au panneau de controle via https://adguardhome:443 dans npm
