version: '3.3'
services:
    ampache:
        container_name: ampache
        labels:
            - "diun.enable=true"
        network_mode: nginx-proxy-manager_default
        volumes:
            - '/home/maxens/ampache:/media:ro'
        ports:
            - '5012:80'
        image: 'ampache/ampache:latest'
