version: '3.2'
services:
  Backup-Portainer:
    container_name: backup
    image: ghcr.io/maxens-git/backup:latest
    hostname: portainer-backup
    restart: unless-stopped
    command: schedule
    environment:
      BACKUP_ENCRYPTION_KEY: "REDACTED_KEY"
      TZ: Europe/Paris #set local timezone using TZ database name standard as seen - https://manpages.ubuntu.com/manpages/bionic/man3/DateTime::TimeZone::Catalog.3pm.html
      PORTAINER_BACKUP_URL: "https://portainer.maxens.tech"
      PORTAINER_BACKUP_TOKEN: "REDACTED_TOKEN"
      PORTAINER_BACKUP_SCHEDULE: "0 0 0 * * *"

    volumes:
      - /docker/npm:/data/npm
      - /docker/vaultwarden:/data/vaultwarden
      - /docker/adguardhome:/data/adguardhome
      - ./config:/config
