version: '3.1'

services:
  db:
    image: mariadb:10.6
    container_name: mariadb
    labels:
      - "diun.enable=true"
    network_mode: nginx-proxy-manager_default
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: REDACTED_PASSWORD

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    labels:
      - "diun.enable=true"
    network_mode: nginx-proxy-manager_default
    restart: always
    ports:
      - 9015:80
    environment:
      - UPLOAD_LIMIT=222K
      - PMA_ARBITRARY=0 #1 pour se connecter a une base de donnée externe
      - PMA_HOST=mariadb
      #- MAX_EXECUTION_TIME = 1000
