version: '3.3'
services:
    server:
        container_name: bitwarden
        labels:
            - diun.enable=true
        network_mode: nginx-proxy-manager_default #Si nginx proxy manager est installé
        volumes:
            - /docker/vaultwarden:/data/
        ports:
            - '5001:80'
        image: 'vaultwarden/server:latest'
        restart: always
        environment:
            - WEBSOCKET_ENABLED=true
            - DOMAIN=https://bitwarden.maxens.tech
            #- SIGNUPS_ALLOWED=True #True pour le premier démarrage
