# Server HTTP port
[server]
http_port = 3000

# Protocol (http, https, or proxy)
protocol = http


#Only if authelia is enable
root_url = https://data.maxensv.me
################################


# Log level (info, debug, error, critical)
log_level = info

# Database configuration
[database]
# Type of database (mysql, postgres, sqlite3, etc.)
type = sqlite3

# Path to the database file (only applicable for SQLite3)
path = /var/lib/grafana/grafana.db

# Grafana user credentials
[security]
admin_user = admin
admin_password = admin

# Data source provisioning
[provisioning.datasources]
# Path to the directory containing the data source configuration files
# (e.g., /etc/grafana/provisioning/datasources)
datasources = /etc/grafana/provisioning/datasources

# Dashboard provisioning
[provisioning.dashboards]
# Path to the directory containing the dashboard configuration files
# (e.g., /etc/grafana/provisioning/dashboards)
dashboards = /etc/grafana/provisioning/dashboards


#Only if authelia is enable
[auth.generic_oauth]
enabled = true
name = Authelia
icon = signin
client_id = grafana
client_secret = REDACTED_CLIENT_SECRET
scopes = openid profile email groups
empty_scopes = false
auth_url = https://auth.maxensv.me/api/oidc/authorization
token_url = https://auth.maxensv.me/api/oidc/token
api_url = https://auth.maxensv.me/api/oidc/userinfo
login_attribute_path = preferred_username
groups_attribute_path = groups
name_attribute_path = name
use_pkce = true
#######################################