version: '3'
services:
  ntfy:
    image: binwiederhier/ntfy
    restart: unless-stopped
    container_name: ntfy
    network_mode: nginx-proxy-manager_default
    environment:
      NTFY_BASE_URL: https://ntfy.maxens.org
      NTFY_CACHE_FILE: /var/lib/ntfy/cache.db
      NTFY_AUTH_FILE: /var/lib/ntfy/auth.db
      NTFY_AUTH_DEFAULT_ACCESS: deny-all
      NTFY_BEHIND_PROXY: true
      NTFY_ATTACHMENT_CACHE_DIR: /var/lib/ntfy/attachments
      NTFY_ENABLE_LOGIN: true #ntfy user add --role=admin maxens
      NTFY_UPSTREAM_BASE_URL: https://ntfy.sh #Ne pas changer l'adresse (notification ios)
      NTFY_WEB_PUSH_FILE: /var/lib/ntfy/webpush.db

    volumes:
      - /docker/ntfy/:/var/lib/ntfy
    ports:
      - 8560:80
    command: serve
