version: '3.8'

services:
  wordpress:
    image: arm64v8/wordpress:latest
    container_name: wordpress
    network_mode: nginx-proxy-manager_default
    restart: unless-stopped
    ports:
      - 8089:80
    environment:
      WORDPRESS_DB_HOST: wordpress_db	
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - /docker/e-portfolio.github.io.wordpress/wordpress_data:/var/www/html
    depends_on:
      - db

  db:
    image: arm64v8/mariadb:latest
    container_name: wordpress_db
    restart: unless-stopped
    network_mode: nginx-proxy-manager_default
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - /docker/e-portfolio.github.io.wordpress/db_data:/var/lib/mysql

volumes:
  wordpress_data:
  db_data:
