version: '3.3'
services:
     minecraft-serve:
        volumes:
            - '/docker/minecraft-spigot/:/data'
        restart: unless-stopped
        environment:
            - TYPE=PAPER
            - EULA=TRUE
            - VERSION=1.21
            - MODE=survival
            - EXEC_DIRECTLY=true
            - MEMORY=5G
            - MAX_PLAYERS=50
            - ONLINE_MODE=true
            #RCON
            #- ENABLE_RCON=${rcon_enable}
            #- RCON_PASSWORD=${rcon_pass}
        ports:
            - '25565:25565'
            #- '8123:8123' dynmap
            #- '8085:8085' webui
        container_name: minecraft-spigot
        network_mode: swag_crowdsec
        image: itzg/minecraft-server

