version: '3'
services:
  smb:
    image: dperson/samba
    container_name: samba
    ports:
      - "139:139"
      - "8121:445"
    volumes:
      - /media/maxens/AISENS/:/smb/
    command: >
      -u "maxens;czq4JEA.jkn4apx2aea"
      -u "films;neh0yvx9xft@AWF7kna"
      -u "luc;JJqo2k4kmGJXEwXdF26M"
      
      -s "maxens;/smb/maxens;no;no;no;maxens"
      -s "films;/smb/films;no;no;no;maxens,luc"
      -s "luc;/smb/luc;no;no;no;luc"
    restart: always
