version: '3.3'
services:
  ampache:
    image: ampache/ampache:latest
    container_name: ampache
    restart: unless-stopped
    network_mode: swag_crowdsec
    ports:
      - 8100:80
    volumes:
      - /docker/ampache/config:/var/www/config
      - /docker/ampache/log:/var/log/ampache
      - /home/ubuntu/Music:/media
      - /docker/ampache/mysql:/var/lib/mysql

      #sudo chown www-data:www-data /docker/ampache/config -R
