---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Raspberry:
    - Portainer:
        iocn: portainer.png
        href: https://192.168.1.47:9443
        description:
        container: portainer
        widget:
          type: portainer
          url: https://192.168.1.47:9443
          env: 2
          key: api
    - Immich:
        href: https://maxens-immich.duckdns.org
        container: immich_server
        widget:
          type: immich
          url: https://maxens-immich.duckdns.org
          key: api
    - Nginx proxy manager:
        href: http://192.168.1.47:81
        container: npm
        widget:
          type: npm
          url: http://192.168.1.47:81
          username: maxens.verron@outlook.com
          password: password

- Oracle:
    - Minecraft:
        href: minecraft://localhost:25565
        description:
        widget:
          type: minecraft
          url: udp://129.158.222.17:25565
#    - Uptime-kuma:
 #       href:
  #      widget:
   #       type: uptimekuma
    #      url: http://129.158.222.17:8050/
     #     slug: statuspageslug

- Others:
    - Nextdns:
        href: my.nextdns.io
        widget:
          type: nextdns
          profile: perso
          key: api
