version: '3'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    network_mode: nginx-proxy-manager_default
    ports:
      - 4101:9090
    volumes:
      - /docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    restart: always
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    network_mode: nginx-proxy-manager_default
    container_name: cadvisor
    ports:
      - 4102:8098
    command:
      - '-port=8098'
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    privileged: true
    restart: unless-stopped
  
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    network_mode: nginx-proxy-manager_default
    ports:
      - 4103:9100
    command: '--path.rootfs=/host'
    pid: host
    restart: unless-stopped
    volumes:
      - /:/host:ro,rslave

  adguard-exporter:
    environment:
      - ADGUARD_SERVERS=https://adguardhome
      - ADGUARD_USERNAMES=maxens
      - ADGUARD_PASSWORDS=REDACTED_PASSWORD
    ports:
      - 4104:9618
    container_name: adguard-exporter
    network_mode: nginx-proxy-manager_default
    image: ghcr.io/henrywhitaker3/adguard-exporter:latest
    #restart: unless-stopped

volumes:
  prometheus-data: {}
