version: '3.3'
services:
     web-ui:
        ports:
            - '8300:80'
        restart: always
        container_name: minecraft-spigot-web-ui
        image: ghcr.io/maxens-git/rcon-web-ui:2.5.1
        
     minecraft-serve:
        volumes:
            - '/docker/minecraft-spigot/:/data'
        environment:
            - TYPE=SPIGOT
            - EULA=TRUE
            - VERSION=1.19.4
            #- MODE=survival
            - EXEC_DIRECTLY=true
            - MEMORY=4G
            - MAX_PLAYERS=50
            - ONLINE_MODE=true
            #RCON
            - ENABLE_RCON=false
            - RCON_PASSWORD=${rcron_pass}
        ports:
            - '25565:25565'
            - '8123:8123'
            - '8085:8085'
        container_name: minecraft-spigot
        image: itzg/minecraft-server

