version: '3.3'
services:
    minecraft-serve:
        volumes:
            - '/docker/minecraft-spigot/:/data'
        environment:
            - TYPE=SPIGOT
            - EULA=TRUE
        ports:
            - '25565:25565'
        container_name: minecraft-spigot
        image: itzg/minecraft-serve
