version: '3.3'
services:
     minecraft-serve:
        volumes:
            - '/docker/minecraft-spigot/:/data'
        environment:
            - TYPE=SPIGOT
            - EULA=TRUE
            - VERSION=1.19.4
            #- MODE=survival
            #- EXEC_DIRECTLY=true
            #- MEMORY=1G
            - MAX_PLAYERS=50
            #- ONLINE_MODE=true
            #RCON
            - ENABLE_RCON=true
            - RCON_PASSWORD=${rcron_pass}
        ports:
            - '25565:25565'
            - '8123:8123'
        container_name: minecraft-spigot
        image: itzg/minecraft-server

