version: '3.1'

services:
  db:
    #image: mariadb:10.6
    image: mysql:latest
    container_name: mysql
    labels:
      - "diun.enable=true"
    network_mode: nginx-proxy-manager_default
    restart: always
    ports:
      - 3306:3306
    volumes:
      - /docker/mysql/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: REDACTED_PASSWORD

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    labels:
      - "diun.enable=true"
    network_mode: nginx-proxy-manager_default
    restart: always
    ports:
      - 8107:80
    environment:
      - UPLOAD_LIMIT=512M
      - MAX_EXECUTION_TIME=10000
      - PMA_ARBITRARY=0 #1 pour se connecter a une base de donnée externe
      - PMA_HOST=mysql
      
