# yamllint disable rule:comments-indentation
---
###############################################################################
#                           Authelia Configuration                            #
###############################################################################

theme: dark #light/dark

identity_validation:
  reset_password:
    jwt_secret: 'REDACTED_SECRET' #any text or number you want to add here to create jwt Token

default_redirection_url: https://google.com #where to redirect for a non-existent URL


server:
  address: tcp://0.0.0.0:9091/

  buffers:
    read: 4096
    write: 4096
  endpoints:
    enable_pprof: false
    enable_expvars: false
  disable_healthcheck: false
  tls:
    key: ""
    certificate: ""

log:
  level: debug

totp:
  issuer: maxens.org #your authelia top-level domain
  period: 30
  skew: 1

authentication_backend:
  password_reset:
    disable: false
  refresh_interval: 5m
  file:
    path: /config/users_database.yml #this is where your authorized users are stored
    password:
      algorithm: argon2id
      iterations: 1
      key_length: 32
      salt_length: 16
      memory: 1024
      parallelism: 8

access_control:
  default_policy: deny
  rules:
    ## bypass rule
    - domain:
        - "auth.maxens.org" #This should be your authentication URL
      policy: bypass
    - domain: "uptime-kuma.maxens.org" #example domain to protect
      policy: two_factor
    - domain: "rasp.duplicati.maxens.org"
      policy: two_factor
    - domain: "netdata.maxens.org"
      policy: two_factor
    - domain: "rasp.netdata.maxens.org"
      policy: two_factor
    - domain: "pyload.maxens.org"
      policy: two_factor

session:
  name: authelia_session
  secret: REDACTED_SECRET #any text or number you want to add here to create jwt Token
  expiration: 3600  # 1 hour
  inactivity: 300  # 5 minutes
  domain: maxens.org  # Should match whatever your root protected domain is

regulation:
  max_retries: 3
  find_time: 10m
  ban_time: 12h

storage:
  local:
    path: /config/db.sqlite3 #this is your databse. You could use a mysql database if you wanted, but we're going to use this one.
  encryption_key: REDACTED_KEY #added Dec 5 2021


notifier:
  disable_startup_check: false
  filesystem:
    filename: "/config/notification.txt"


identity_providers:
  oidc:
    hmac_secret: 'REDACTED_HMAC_SECRET' #chaine de 64 caractères
    jwks:
      - key_id: 'maxens'
        algorithm: 'RS256'
        use: 'sig'
        key: |
          -----BEGIN PRIVATE KEY-----
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          -----END PRIVATE KEY-----
        certificate_chain: |
          -----BEGIN CERTIFICATE-----
          MIIC5TCCAc2gAwIBAgIQENxwbRCShVurct/m2S1N8jANBgkqhkiG9w0BAQsFADAT
          MREwDwYDVQQKEwhBdXRoZWxpYTAeFw0yNDA0MzAxNTU2MTNaFw0yNTA0MzAxNTU2
          MTNaMBMxETAPBgNVBAoTCEF1dGhlbGlhMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8A
          MIIBCgKCAQEAy4/LAJgN9G84OgS31YpOUyHcoYQc6FFF8CSLLq2OWt3PaTfY+TFN
          3SE+81lHlgEY5lW466O1kadi5Z5/JlTRQvT0cCDG2t7ADxsvKm5t2KrH1Mvc8KE/
          KvdKbDr3ssj9iEuI+ra57KUS0s/+aZ0wuy6gIWVJuaN7pky0m8MZGV0hDq2cXQx1
          km3heKbyRtg4rvBoaNdA7MvY7DUfCPG7/jcjsfz/4mRy7zKY9Mj2bWluspan29vL
          8cV2QfsfweymkiAM+1WlYUV/XbrFr7dqZtQg+N1JmG8hTc7XJ7gcliDINgFOx0p9
          QROWYbaxovkVQZVtPlqAQj6eY8m8YaAcowIDAQABozUwMzAOBgNVHQ8BAf8EBAMC
          BaAwEwYDVR0lBAwwCgYIKwYBBQUHAwEwDAYDVR0TAQH/BAIwADANBgkqhkiG9w0B
          AQsFAAOCAQEADGMqthdhESsoqijMuDOCcyyc9XRQh0NOwroBOvQYBhxDPsax+gyu
          xmNbI5FvqplCiDgd58PkJ1/DNqcjWzEqxwthb3QpX9nRNlsM8Zv3ntcz75uHo10m
          ZkD03icAgOBK5d8ZCsnksEjrYBAM5eCmj1zNggD22Ry1ncnRBuB7EqXGA+UjaC19
          JYUSc+oX0kbWPUuMxh0YJ3L8/t30NBbWNyzMKxK0xmjBMXKoI+VzXvFIlZkogz9x
          0d8QfLcc1u6f3lM9wqkb6w6xrZdxzE9TR8Xam4nozFwQ09JWzSTiYNZnDU2f1rE0
          NkTD9B3xhhCHUoTBCg4z47DUFhqP5Duazw==
          -----END CERTIFICATE-----
    enable_client_debug_messages: false
    minimum_parameter_entropy: 8
    enforce_pkce: 'public_clients_only'
    enable_pkce_plain_challenge: false
    enable_jwt_access_token_stateless_introspection: false
    discovery_signed_response_alg: 'none'
    discovery_signed_response_key_id: ''
    require_pushed_authorization_requests: false
    authorization_policies:
      policy_name:
        default_policy: 'two_factor'
        rules:
          - policy: 'deny'
            subject: 'group:services'
    lifespans:
      access_token: '1h'
      authorize_code: '1m'
      id_token: '1h'
      refresh_token: '90m'
    cors:
      endpoints:
        - 'authorization'
        - 'token'
        - 'revocation'
        - 'introspection'
      allowed_origins_from_client_redirect_uris: false
    clients:
      - client_id: 'portainer'
        client_name: 'Portainer'
        client_secret: '$pbkdf2-sha512$310000$DB7sOAAmXiqRJaZ9HFD/UQ$Izgo2Dg2Fh7Qc4cc3pb.qsxkzWB8XwHUTPnSRSCe.CdwwdW.Yu8TtiZRkRyUCd1nk4UBNcONZo30hov6Az0ktA'  # The digest of 'insecure_secret'.
        public: false
        authorization_policy: 'two_factor'
        redirect_uris:
          - 'https://docker.maxens.org/'
        scopes:
          - 'openid'
          - 'profile'
          - 'groups'
          - 'email'
        userinfo_signed_response_alg: 'none'

      - client_id: 'immich'
        client_name: 'immich'
        client_secret: '$pbkdf2-sha512$310000$HUUo.pRES1G3xUGoedkMhA$i57mktLgnOLacBBdt6w4kCbVR4aKDEaEHXGEIhkwrIMnjj4yIL./lY1WN4P5YQvS6kax60hfjME6GNOJbTLKtQ'  # The digest of 'insecure_secret'.
        public: false
        authorization_policy: 'two_factor'
        redirect_uris:
          - 'https://immich.maxens.org/auth/login'
          - 'https://immich.maxens.org/user-settings'
          - 'app.immich:/'
        scopes:
          - 'openid'
          - 'profile'
          - 'email'
        userinfo_signed_response_alg: 'none'

      - client_id: 'portainer-raspberry'
        client_name: 'Portainer'
        client_secret: '$pbkdf2-sha512$310000$YpOM60Jwn/fbf6gt1y5nsA$1VDpTqIpzlSI.qCTgUenXQsOf8ys/e96lM.N8lJlmLvsioIxglfxCkrjkCrAuR8wH7C4tmGm2C88rZn3GAAWnA'  # The digest of 'insecure_secret'.
        public: false
        authorization_policy: 'two_factor'
        redirect_uris:
          - 'https://rasp.docker.maxens.org/'
        scopes:
          - 'openid'
          - 'profile'
          - 'groups'
          - 'email'
        userinfo_signed_response_alg: 'none'
