version: "3"

services:
  authelia:
    container_name: "authelia"
    image: "authelia/authelia:latest"
    restart: unless-stopped
    network_mode: nginx-proxy-manager_default
    ports:
      - 9091:9091
    volumes:
      - /docker/authelia/:/config
