version: '3.7'

services:
  nextcloud:
    image: nextcloud
    container_name: nextcloud
    restart: always
    ports:
      - 8998:80
    volumes:
      - /media/maxens/595bf993-a269-47a4-bb20-5694dc30f194/data:/var/www/html
    environment:
      - MYSQL_PASSWORD=mdp
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=maxens
      - MYSQL_HOST=db
      - NEXTCLOUD_TRUSTED_DOMAINS=files.maxens.org
      - OVERWRITEPROTOCOL=https #SI REVERSE PROXY + HTTPS
      - OVERWRITECLIURL=https://files.maxens.org #SI REVERSE PROXY + HTTPS
    depends_on:
      - db

  db:
    image: mariadb
    container_name: nextcloud-db
    restart: always
    volumes:
      - /media/maxens/595bf993-a269-47a4-bb20-5694dc30f194/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mdp1
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=maxens
      - MYSQL_PASSWORD=mdp
    
