version: '3.7'

services:
  nextcloud:
    image: nextcloud
    container_name: nextcloud
    ports:
      - 8998:80
    volumes:
      - /media/maxens/AISENS2/nextcloud/nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=PASSWORD
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=maxens
      - MYSQL_HOST=db
      - NEXTCLOUD_TRUSTED_DOMAINS=cloud.maxens.org
      - OVERWRITEPROTOCOL=https
      - OVERWRITECLIURL=https://cloud.maxens.org
    depends_on:
      - db

  db:
    image: mariadb
    container_name: nextcloud-db
    restart: always
    volumes:
      - /media/maxens/AISENS2/nextcloud/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=ROOTPASWWORD
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=maxens
      - MYSQL_PASSWORD=PASSWORD
    
