services:
 tinyauth:
    container_name: tinyauth
    image: ghcr.io/steveiliop56/tinyauth:v3
    restart: unless-stopped
    environment:
      - SECRET=${TINYAUTH_SECRET}
      - APP_URL=http://auth.maxens.org
      - USERS=${TINYAUTH_USERS}
    ports:
      - 3999:3000
