version: '3'

services:
  crafty:
    container_name: crafty_container
    image: registry.gitlab.com/crafty-controller/crafty-4:latest
    network_mode: nginx-proxy-manager_default
    restart: always
    environment:
        - TZ=Etc/UTC
    ports:
        - "8999:8000" # HTTP
        - "8449:8443" # HTTPS
        #- "8123:8123" # DYNMAP
        #- "19132:19132/udp" # BEDROCK
        - "25560:25565" # MC SERV PORT RANGE
    volumes:
        - /docker/crafty/backups:/crafty/backups
        - /docker/crafty/logs:/crafty/logs
        - /docker/crafty/servers:/crafty/servers
        - /docker/crafty/config:/crafty/app/config
        - /docker/minecraft-spigot:/crafty/import
